export const TEST_COMMENTS = [
    'Всё отлично!',
    'В целом всё неплохо. Но не всё.',
    'Когда вы делаете фотографию, хорошо бы убирать палец из кадра. В конце концов это просто непрофессионально.',
    'Моя бабушка случайно чихнула с фотоаппаратом в руках и у неё получилась фотография лучше.',
    'Я поскользнулся на банановой кожуре и уронил фотоаппарат на кота и у меня получилась фотография лучше.',
    'Лица у людей на фотке перекошены, как будто их избивают. Как можно было поймать такой неудачный момент?!'
  ],
  TEST_NAMES = [
    'Кирилл',
    'Евгений',
    'Артем',
    'Артур',
    'Александр',
    'Михаил',
    'Ксения',
    'Алена',
    'Арина',
    'Алина',
    'Петр',
    'Ульяна',
    'Анна',
    'Григорий'
  ],
  TEST_DESCRIPTIONS = [
    'С волками жить - по волчьи выть.',
    'Настоящая братва - это единицы из сотен, что своих не бросали.',
    'Друзей выбираем мы сами, но лучших оставляет время.',
    'Мне не важно прав он или нет, он мой брат, и я тебя за него разорву!',
    'Своя компания - это компания, в которой можно не думать когда говоришь.',
    'Живи, братуха, и не думай, что кто-то про тебя забыл. Друзья не забывают друга, а кто забыл, тот не был им.'
  ],
  COMMENT_TEMPLATE = document.querySelector('#comments'),
  PICTURE_TEMPLATE = document.querySelector('#picture'),
  UPLOAD_FORM_ELEMENT = document.querySelector('#upload-select-image'),
  UPLOAD_FORM_OVERLAY_ELEMENT = document.querySelector('.img-upload__overlay'),
  UPLOAD_FILE_ELEMENT = document.querySelector('#upload-file'),
  UPLOAD_CANCEL_ELEMENT = document.querySelector('#upload-cancel'),
  EFFECTS_PREVIEW_ELEMENTS = document.querySelectorAll('.effects__preview'),
  SCALE_VALUE_ELEMENT = document.querySelector('.scale__control--value'),
  HASHTAGS_ELEMENT = document.querySelector('.text__hashtags'),
  DESCRIPTION_ELEMENT = document.querySelector('.text__description'),
  EFFECT_LEVEL_ELEMENT = document.querySelector('.effect-level'),
  EFFECT_SLIDER_ELEMENT = document.querySelector('.effect-level__slider'),
  EFFECT_LEVEL_VALUE_ELEMENT = document.querySelector('.effect-level__value'),
  EFFECT_FILTER_RADIOS = document.querySelectorAll('.effects__radio'),
  EFFECT_SCALE_CONTROL_BIGGER_ELEMENT = document.querySelector('.scale__control--bigger'),
  EFFECT_SCALE_CONTROL_SMALLER_ELEMENT = document.querySelector('.scale__control--smaller'),
  IMAGE_FILTERS_ELEMENT = document.querySelector('.img-filters'),
  BIG_PICTURE_ELEMENT = document.querySelector('.big-picture'),
  BIG_PICTURE_IMG_ELEMENT = document.querySelector('.big-picture__img'),
  BIG_PICTURE_LIKES_COUNT_ELEMENT = document.querySelector('.likes-count'),
  BIG_PICTURE_COMMENTS_COUNT_ELEMENT = document.querySelector('.comments-count'),
  BIG_PICTURE_DESCRIPTION_ELEMENT = document.querySelector('.social__caption'),
  BIG_PICTURE_CANCEL_ELEMENT = document.querySelector('.big-picture__cancel'),
  COMMENTS_ELEMENT = document.querySelector('.social__comments'),
  COMMENTS_COUNT_ELEMENT = document.querySelector('.social__comment-count'),
  COMMENTS_LOADER_ELEMENT = document.querySelector('.comments-loader'),
  PICTURES_ELEMENT = document.querySelector('.pictures'),
  PICTURES_ELEMENTS = document.querySelectorAll('.picture'),
  ALERT_ELEMENT = document.querySelector('.alert'),
  ALERT_MESSAGE_ELEMENT = document.querySelector('.alert__message'),
  ALERT_TITLE_ELEMENT = document.querySelector('.alert__title'),
  EFFECTS_FILTERS = {
    'chrome': {
      min: 0,
      max: 1,
      current: 1,
      step: 0.1,
      filter: (value) => `grayscale(${value})`,
    },
    'sepia': {
      min: 0,
      max: 1,
      current: 1,
      step: 0.1,
      filter: (value) => `sepia(${value})`,
    },
    'marvin': {
      min: 0,
      max: 100,
      current: 100,
      step: 1,
      filter: (value) => `invert(${value}%)`,
    },
    'phobos': {
      min: 0,
      max: 3,
      current: 3,
      step: 0.1,
      filter: (value) => `blur(${value}px)`,
    },
    'heat': {
      min: 0,
      max: 3,
      current: 3,
      step: 0.1,
      filter: (value) => `brightness(${value})`,
    },
  },
  IMAGE_SCALE_MIN = 25,
  IMAGE_SCALE_MAX = 100,
  IMAGE_SCALE_STEP = 25,
  HASHTAG_REGEX = /^#[a-zа-яё0-9]{1,19}$/i,
  API_URI = 'https://28.javascript.pages.academy/kekstagram',
  FILE_TYPES = ['jpg', 'jpeg', 'png'];
